IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'color_name')
BEGIN
    ALTER TABLE dbo.resep_obat ADD color_name VARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'color_desc')
BEGIN
    ALTER TABLE dbo.resep_obat ADD color_desc VARCHAR(255);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'speed')
BEGIN
    ALTER TABLE dbo.resep_obat ADD speed DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'temperature')
BEGIN
    ALTER TABLE dbo.resep_obat ADD temperature DECIMAL(18,2) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'nilai_l')
BEGIN
    ALTER TABLE dbo.resep_obat ADD nilai_l DECIMAL(18,4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'nilai_a')
BEGIN
    ALTER TABLE dbo.resep_obat ADD nilai_a DECIMAL(18,4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'nilai_b')
BEGIN
    ALTER TABLE dbo.resep_obat ADD nilai_b DECIMAL(18,4) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'lampiran_path')
BEGIN
    ALTER TABLE dbo.resep_obat ADD lampiran_path VARCHAR(255) NULL;
END
