<?php
session_start(); date_default_timezone_set('Asia/Jakarta'); header('Content-Type: application/json; charset=utf-8'); $requestId=bin2hex(random_bytes(8));
function auditApiOut(int $status,array $data):void{global $requestId;http_response_code($status);echo json_encode(array_merge(['request_id'=>$requestId],$data),JSON_UNESCAPED_UNICODE);exit;}
function auditApiLog(Throwable $e):void{global $requestId;$dir=__DIR__.'/../../../logs';if(!is_dir($dir))@mkdir($dir,0775,true);$entry=['timestamp'=>date(DATE_ATOM),'severity'=>'ERROR','request_id'=>$requestId,'module'=>'ppc_guidance/resep_obat','action'=>'audit_detail_resep','user'=>$_SESSION['UserName']??null,'message'=>'Gagal memuat audit detail resep.','source'=>basename(__FILE__),'context'=>['exception'=>get_class($e)]];@file_put_contents($dir.'/error-'.date('Y-m-d').'.log',json_encode($entry,JSON_UNESCAPED_UNICODE).PHP_EOL,FILE_APPEND|LOCK_EX);}
if(!isset($_SESSION['UserName']))auditApiOut(401,['ok'=>false,'message'=>'Sesi login telah berakhir.']);
require_once __DIR__.'/debug_detail_resep_compare.php';
function auditApiRoutes(): array { global $conn;$s=sqlsrv_query($conn,"SELECT LTRIM(RTRIM(ISNULL(NULLIF(rtg_code,''),'-'))) code,MAX(NULLIF(LTRIM(RTRIM(rtg_name)),'-')) name,COUNT(*) total FROM dbo.resep_obat WHERE NULLIF(LTRIM(RTRIM(no_cp)),'') IS NOT NULL AND no_cp<>'-' GROUP BY LTRIM(RTRIM(ISNULL(NULLIF(rtg_code,''),'-'))) ORDER BY code");if(!$s)throw auditSqlError('Gagal mengambil routing');$rows=[];while($r=sqlsrv_fetch_array($s,SQLSRV_FETCH_ASSOC))$rows[]=$r;return $rows;}
try{$action=$_GET['action']??'list';if($action==='detail'){$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$bon=filter_input(INPUT_GET,'bonreq_id',FILTER_VALIDATE_INT)?:null;if(!$id) auditApiOut(422,['ok'=>false,'message'=>'ID resep tidak valid.']);$r=auditFindRecipe($id);if(!$r)auditApiOut(404,['ok'=>false,'message'=>'Resep tidak ditemukan.']);auditApiOut(200,['ok'=>true,'audit'=>auditRecipe($r,$bon,true)]);}if($action==='audit_batch'){$raw=explode(',',(string)($_GET['ids']??''));$ids=array_values(array_unique(array_filter(array_map('intval',$raw),fn($id)=>$id>0)));if(!$ids||count($ids)>5)auditApiOut(422,['ok'=>false,'message'=>'Batch audit harus berisi 1 sampai 5 ID resep.']);$rows=[];foreach($ids as $id){$r=auditFindRecipe($id);if(!$r)continue;$a=auditRecipe($r,null,true);$rows[]=['id'=>$id,'no_cp'=>$r['no_cp'],'cus_color'=>$r['cus_color'],'rtg_code'=>$r['rtg_code'],'rtg_name'=>$r['rtg_name'],'is_manual'=>$r['is_manual'],'status_resep_lipat'=>$r['status_resep_lipat'],'created_at'=>$r['created_at'],'status'=>$a['status'],'status_detail'=>$a['status_detail'],'source'=>$a['source'],'candidate_count'=>count($a['candidates']),'bonno'=>$a['selected_bon']['bonno']??'','proint_rtgname'=>$a['selected_bon']['rtgname']??''];}auditApiOut(200,['ok'=>true,'rows'=>$rows]);}
$filters=['cp'=>trim((string)($_GET['cp']??'')),'source'=>strtoupper(trim((string)($_GET['source']??''))),'start'=>trim((string)($_GET['start']??'')),'end'=>trim((string)($_GET['end']??''))];
if($action==='routes')auditApiOut(200,['ok'=>true,'routes'=>auditApiRoutes()]);
if($action==='ids'){$first=auditLocalRows($filters,0,1);if(!$first['total'])auditApiOut(200,['ok'=>true,'ids'=>[],'total'=>0]);$all=auditLocalRows($filters,0,$first['total']);auditApiOut(200,['ok'=>true,'ids'=>array_map(fn($r)=>(int)$r['id'],$all['rows']),'total'=>$first['total']]);}
$page=max(1,(int)($_GET['page']??1));$limit=25;$data=auditLocalRows($filters,($page-1)*$limit,$limit);$rows=[];foreach($data['rows'] as $r)$rows[]=['recipe'=>$r,'status'=>'MENUNGGU','status_detail'=>'Menunggu pemeriksaan ProInt','source'=>'','candidate_count'=>0,'bonno'=>''];auditApiOut(200,['ok'=>true,'rows'=>$rows,'total'=>$data['total'],'page'=>$page,'limit'=>$limit]);}catch(Throwable $e){auditApiLog($e);auditApiOut(500,['ok'=>false,'message'=>'Gagal memuat audit detail resep.']);}
