<?php
session_start();if(!isset($_SESSION['UserName'])){http_response_code(401);exit('Access denied');}require_once __DIR__.'/../../../vendor/autoload.php';require_once __DIR__.'/debug_detail_resep_compare.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;use PhpOffice\PhpSpreadsheet\Style\Fill;use PhpOffice\PhpSpreadsheet\Style\Alignment;
set_time_limit(300);
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $payload = json_decode(file_get_contents('php://input'), true);
    $rows = is_array($payload['rows'] ?? null) ? $payload['rows'] : [];
    if (!$rows || count($rows) > 10000) {
        http_response_code(422);
        exit('Hasil audit kosong atau melebihi batas 10.000 baris.');
    }
    $book = new Spreadsheet();$sum=$book->getActiveSheet();$sum->setTitle('Ringkasan Audit');
    $sum->fromArray(['ID Lokal','No CP','Routing Lokal','Sumber Resep','Status Resep','Dibuat','Bon ProInt','Routing ProInt','Status Audit','Keterangan'],null,'A1');
    $sr=2;foreach($rows as $r){$sum->fromArray([(int)($r['id']??0),$r['no_cp']??'',trim(($r['rtg_code']??'').' - '.($r['rtg_name']??''),' -'),(int)($r['is_manual']??0)===1?'MANUAL':'PROINT',$r['status_resep_lipat']??'-',$r['created_at']??'',$r['bonno']??'',$r['proint_rtgname']??'',$r['status']??'',$r['status_detail']??''],null,'A'.$sr++);}
    $sum->getStyle('A1:J1')->applyFromArray(['font'=>['bold'=>true,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'1F4E78']],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER]]);$sum->freezePane('A2');$sum->setAutoFilter('A1:J'.($sr-1));foreach(range('A','J') as $c)$sum->getColumnDimension($c)->setAutoSize(true);
    $filename='Audit_Ringkasan_Resep_'.date('Ymd_His').'.xlsx';while(ob_get_level())ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: max-age=0');(new Xlsx($book))->save('php://output');exit;
}
$filters=['cp'=>trim((string)($_GET['cp']??'')),'source'=>strtoupper(trim((string)($_GET['source']??''))),'start'=>trim((string)($_GET['start']??'')),'end'=>trim((string)($_GET['end']??''))];$book=new Spreadsheet();$sum=$book->getActiveSheet();$sum->setTitle('Ringkasan');$headers=['ID Lokal','No CP','Routing Lokal','Sumber','Dibuat','Bon ProInt','Routing ProInt','Status'];$sum->fromArray($headers,null,'A1');$detail=$book->createSheet();$detail->setTitle('Perbandingan Detail');$dh=['ID Lokal','No CP','Bon ProInt','Kode Obat','Nama','Kategori','Qty Lokal','Qty ProInt','Selisih Qty','CF Lokal','CF ProInt','Selisih CF','UOM Lokal','UOM ProInt','Status'];$detail->fromArray($dh,null,'A1');$sr=2;$dr=2;$offset=0;$limit=100;
do{$batch=auditLocalRows($filters,$offset,$limit);foreach($batch['rows'] as $r){$a=auditRecipe($r,null,true);$b=$a['selected_bon'];$sum->fromArray([$r['id'],$r['no_cp'],$r['rtg_code'].' - '.$r['rtg_name'],(int)$r['is_manual']===1?'MANUAL':'PROINT',$r['created_at'],$b['bonno']??'',$b['rtgname']??'',$a['status']],null,'A'.$sr++);if(!$a['details']){$detail->fromArray([$r['id'],$r['no_cp'],$b['bonno']??'','','','','','','','','','','','',$a['status']],null,'A'.$dr++);}foreach($a['details'] as $x){$l=$x['local']??[];$p=$x['proint']??[];$detail->fromArray([$r['id'],$r['no_cp'],$b['bonno']??'',$x['kode'],$l['name']??$p['name']??'',$l['category']??$p['category']??'',$l['receipe']??null,$p['qty']??null,isset($l['receipe'],$p['qty'])?(float)$l['receipe']-(float)$p['qty']:null,$l['cf']??null,$p['cf']??null,isset($l['cf'],$p['cf'])?(float)$l['cf']-(float)$p['cf']:null,$l['uom']??'',$p['uom']??'',$x['status']],null,'A'.$dr++);}}$offset+=count($batch['rows']);}while($offset<$batch['total']&&count($batch['rows'])>0);
foreach([$sum,$detail] as $sheet){$last=$sheet->getHighestColumn();$sheet->getStyle('A1:'.$last.'1')->applyFromArray(['font'=>['bold'=>true,'color'=>['rgb'=>'FFFFFF']],'fill'=>['fillType'=>Fill::FILL_SOLID,'startColor'=>['rgb'=>'1F4E78']],'alignment'=>['horizontal'=>Alignment::HORIZONTAL_CENTER]]);$sheet->freezePane('A2');$sheet->setAutoFilter('A1:'.$last.$sheet->getHighestRow());foreach(range('A',$last) as $c)$sheet->getColumnDimension($c)->setAutoSize(true);}
$filename='Audit_Detail_Resep_'.date('Ymd_His').'.xlsx';header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: max-age=0');(new Xlsx($book))->save('php://output');exit;
