IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'color_name')
BEGIN
    ALTER TABLE dbo.resep_obat ADD color_name VARCHAR(100);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'resep_obat' AND COLUMN_NAME = 'color_desc')
BEGIN
    ALTER TABLE dbo.resep_obat ADD color_desc VARCHAR(255);
END
