<?php
declare(strict_types=1);

session_start();

// helper + koneksi
require_once __DIR__ . '/../_shared/siin_lib.php';

// Autoload Composer
$autoload = realpath(__DIR__ . '/../../../vendor/autoload.php');
if (!$autoload || !is_file($autoload)) {
    http_response_code(500);
    die('Library PDF tidak ditemukan. Pastikan vendor/autoload.php tersedia.');
}
require_once $autoload;

use Dompdf\Dompdf;

if (!isset($_SESSION['UserName'])) {
    $_SESSION['error'] = 'Silakan login terlebih dahulu!';
    header('Location: /login.php');
    exit;
}

$startDate = trim($_GET['start_date'] ?? '');
$endDate   = trim($_GET['end_date'] ?? '');
$where = ' WHERE 1=1 ';
$params = [];

if ($startDate !== '') {
    $where .= ' AND ir_date >= ?';
    $params[] = dmY_to_Ymd($startDate);
}
if ($endDate !== '') {
    $where .= ' AND ir_date <= ?';
    $params[] = dmY_to_Ymd($endDate);
}

$sql = "SELECT ir_date, request_no, descr, status FROM siin_ir $where ORDER BY ir_date DESC, id DESC";
$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

function escapeText(string $text): string {
    return htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
}

$filters = [];
if ($startDate !== '') {
    $filters[] = 'Start Date: ' . escapeText($startDate);
}
if ($endDate !== '') {
    $filters[] = 'End Date: ' . escapeText($endDate);
}
$filterText = $filters ? implode(' | ', $filters) : 'Semua data';

$html = '<html><head><meta charset="utf-8"><style>' .
'body{font-family:Arial,sans-serif;font-size:10pt;margin:0;padding:0;} ' .
'.page{padding:20px;} ' .
'h1{font-size:16pt;margin-bottom:0.25rem;} ' .
'.subtitle{font-size:10pt;margin:0 0 12px 0;color:#333;} ' .
'table{border-collapse:collapse;width:100%;margin-top:10px;} ' .
'th,td{border:1px solid #333;padding:6px 8px;vertical-align:top;} ' .
'th{background:#f1f1f1;text-align:left;} ' .
'td.description{white-space:pre-wrap;word-wrap:break-word;} ' .
'.footer{margin-top:16px;font-size:9pt;color:#555;}' .
'</style></head><body><div class="page">' .
'<h1>Penerimaan Barang Stock IT</h1>' .
'<div class="subtitle">' . escapeText($filterText) . ' | Dicetak: ' . date('d-m-Y H:i') . '</div>' .
'<table><thead><tr>' .
'<th style="width:8%;">No</th>' .
'<th style="width:14%;">Tanggal</th>' .
'<th style="width:20%;">Request No</th>' .
'<th style="width:40%;">Deskripsi</th>' .
'<th style="width:18%;">Status</th>' .
'</tr></thead><tbody>';

if (count($rows) === 0) {
    $html .= '<tr><td colspan="5" style="text-align:center;padding:20px;">Tidak ada data IR.</td></tr>';
} else {
    $index = 1;
    foreach ($rows as $row) {
        $dateText = Ymd_to_dmY($row['ir_date']);
        $status = escapeText($row['status'] ?? '');
        $html .= '<tr>' .
                 '<td style="text-align:center;">' . $index++ . '</td>' .
                 '<td>' . escapeText($dateText) . '</td>' .
                 '<td>' . escapeText($row['request_no'] ?? '') . '</td>' .
                 '<td class="description">' . escapeText($row['descr'] ?? '') . '</td>' .
                 '<td>' . escapeText($status) . '</td>' .
                 '</tr>';
    }
}

$html .= '</tbody></table>' .
'<div class="footer">Generated by SI-IIN IR module.</div>' .
'</div></body></html>';

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

$filename = 'Penerimaan_Barang_Stock_IT_' . date('Ymd_His') . '.pdf';
$dompdf->stream($filename, ['Attachment' => true]);
exit;
