<?php
require_once __DIR__ . '/planning_tv_log.php';
const PLANNING_TV_COOKIE='planning_tv_device'; const PLANNING_TV_REGISTRY=__DIR__.'/planning_tv_devices.json';
function planning_tv_cookie_options(int $expires): array { return ['expires'=>$expires,'path'=>'/gg_app/pages/planning/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']; }
function planning_tv_with_registry(callable $callback) { $h=@fopen(PLANNING_TV_REGISTRY,'c+'); if(!$h||!flock($h,LOCK_EX)){if($h)fclose($h); throw new RuntimeException('Registry perangkat TV tidak dapat dikunci.');} try{rewind($h);$devices=json_decode(stream_get_contents($h)?:'[]',true);if(!is_array($devices))$devices=[];$result=$callback($devices);if(!empty($result['write'])){rewind($h);ftruncate($h,0);fwrite($h,json_encode($devices,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));fflush($h);}return $result['value']??null;}finally{flock($h,LOCK_UN);fclose($h);} }
function planning_tv_register_device(string $username,string $label=''): array { $token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$id=bin2hex(random_bytes(8));$now=date(DATE_ATOM);$label=trim($label)?:'Smart TV';$groupId=(int)($_SESSION['GroupId']??0);$theme=(string)($_SESSION['Theme']??'primary');planning_tv_with_registry(function(&$d)use($id,$hash,$username,$label,$now,$groupId,$theme){$d[$id]=['token_hash'=>$hash,'label'=>substr($label,0,80),'created_by'=>$username,'group_id'=>$groupId,'theme'=>substr($theme,0,30),'created_at'=>$now,'last_used_at'=>$now,'revoked_at'=>null];return['write'=>true,'value'=>true];});setcookie(PLANNING_TV_COOKIE,$id.'.'.$token,planning_tv_cookie_options(time()+(86400*365*20)));return['id'=>$id,'label'=>$label,'created_by'=>$username,'group_id'=>$groupId,'theme'=>$theme]; }
function planning_tv_auth_result(): array { $credential=$_COOKIE[PLANNING_TV_COOKIE]??'';if($credential==='')return['ok'=>false,'reason'=>'cookie_missing','device'=>null];if(!preg_match('/^([a-f0-9]{16})\.([a-f0-9]{64})$/',$credential,$p))return['ok'=>false,'reason'=>'cookie_malformed','device'=>null];[, $id,$token]=$p;try{return planning_tv_with_registry(function(&$d)use($id,$token){$device=$d[$id]??null;if(!$device)return['write'=>false,'value'=>['ok'=>false,'reason'=>'device_not_found','device_id'=>$id,'device'=>null]];if(!empty($device['revoked_at']))return['write'=>false,'value'=>['ok'=>false,'reason'=>'device_revoked','device_id'=>$id,'device'=>null]];if(!hash_equals((string)($device['token_hash']??''),hash('sha256',$token)))return['write'=>false,'value'=>['ok'=>false,'reason'=>'token_mismatch','device_id'=>$id,'device'=>null]];$write=empty($device['last_used_at'])||strtotime((string)$device['last_used_at'])<time()-3600;if($write)$d[$id]['last_used_at']=date(DATE_ATOM);unset($device['token_hash']);$device['id']=$id;return['write'=>$write,'value'=>['ok'=>true,'reason'=>'valid_tv_token','device_id'=>$id,'device'=>$device]];});}catch(Throwable $e){planning_tv_log('ERROR','registry_auth_failure',['auth_reason'=>'registry_unreadable','device_id'=>$id,'message'=>'Registry perangkat tidak tersedia','source_file'=>__FILE__,'source_line'=>__LINE__]);return['ok'=>false,'reason'=>'registry_unreadable','device_id'=>$id,'device'=>null];} }
function planning_tv_authenticate(): ?array { $result=planning_tv_auth_result();return $result['ok']?$result['device']:null; }
function planning_tv_revoke_current_device(): bool { $credential=$_COOKIE[PLANNING_TV_COOKIE]??'';$id=preg_match('/^([a-f0-9]{16})\./',$credential,$p)?$p[1]:'';$revoked=false;if($id!=='')$revoked=planning_tv_with_registry(function(&$d)use($id){if(!isset($d[$id]))return['write'=>false,'value'=>false];$d[$id]['revoked_at']=date(DATE_ATOM);return['write'=>true,'value'=>true];});setcookie(PLANNING_TV_COOKIE,'',planning_tv_cookie_options(time()-3600));return $revoked; }
function planning_tv_has_read_access(): bool { return isset($_SESSION['UserName'])||planning_tv_authenticate()!==null; }
function planning_tv_unauthorized(): void { $result=planning_tv_auth_result();$requestId=planning_tv_log('SECURITY','api_unauthorized',['auth_reason'=>$result['reason'],'device_id'=>$result['device_id']??'','message'=>'Planning TV read authorization failed','source_file'=>__FILE__,'source_line'=>__LINE__]);header('Content-Type: application/json; charset=utf-8');http_response_code(401);echo json_encode(['error'=>'Unauthorized','tv_authorization_required'=>true,'request_id'=>$requestId]);exit; }
